# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='modification_date'),
        ),
        migrations.AddField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation_date'),
        ),
    ]
