"""
Django settings for social_n project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.core.urlresolvers import reverse_lazy

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTER_URL = os.path.join(BASE_DIR, 'templates/register.html')
#LOGIN_URL = reverse_lazy('login')
#LOGOUT_URL = reverse_lazy('logout')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3qq7l3ffe$+=#djyi_0wqf)5(3w+kns1i9%v^$=7+jx=yb*+c3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social.apps.django_app.default',
    'oauth2_provider',
    'corsheaders',
    'webpack_loader',
    'argonauts',
    'widget_tweaks',
    'rest_framework',
    'rest_framework.authtoken',
    'adjacent',
    'chat',
    'base',
    'community',
    'event',
    'friends',
    'login',
    'like',
    'message',
    'photo',
    'user_profile',
    'comment',
]

CENTRIFUGE_ADDRESS = 'http://centrifuge.example.com'
CENTRIFUGE_SECRET = 'your secret key from Centrifugo'
CENTRIFUGE_TIMEOUT = 10

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    #'django.middleware.common.CommonMiddleware'
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'login.middleware.UpdateLastActivityMiddleware',
]
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'social_n.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'adjacent.context_processors.main',
            ],
        },
    },
]

CENTRIFUGE_ADDRESS = 'http://localhost:8000'
CENTRIFUGE_SECRET = 'fd95d9fd-2f06-4e5c-86c9-96a89fc5d37f'
CENTRIFUGE_TIMEOUT = 10

WSGI_APPLICATION = 'social_n.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {

}


AUTHENTICATION_BACKENDS = (
    'social.backends.vk.VKOAuth2',
    #'social.backends.facebook.FacebookOAuth2'
    'oauth2_provider.backends.OAuth2Backend',
    'django.contrib.auth.backends.ModelBackend',
)


MIDDLEWARE_CLASSES = (
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
    'login.middleware.UpdateLastActivityMiddleware',
)


# what to do with an info of concrete user when he has authentificated using social network
# SOCIAL_AUTH_PIPELINE = ()


# -----VK PYTHON-SOCIAL PARAMS-----
# what we ask fro user to go to vk for info access
SOCIAL_AUTH_VK_OAUTH2_SCORE = ['email', ]
# what we ask vk to give to us when we went back to vk with access token got from user
SOCIAL_AUTH_VK_OAUTH2_EXTRA_DATA = ['email', ]

SOCIAL_AUTH_VK_OAUTH2_KEY = '5666968'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'KsranxovgEBuA5IRRdAf'

# -----FACEBOOK PYTHON-SOCIAL PARAMS-----
# what we ask fro user to go to vk for info access
SOCIAL_AUTH_FACEBOOK_SCORE = ['email', ]
# what we ask vk to give to us when we went back to vk with access token got from user
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = ['email', ]
# TODO:
'''
SOCIAL_AUTH_FACEBOOK_KEY = '5666968'
SOCIAL_AUTH_FACEBOOK_SECRET = 'KsranxovgEBuA5IRRdAf'

SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
SOCIAL_AUTH_SANITIZE_REDIRECTS = False
'''




LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR+'/collected_static/'
STATICFILES_DIRS = (BASE_DIR+'/static/',
                    os.path.join(BASE_DIR, 'assets'),)


from celery.schedules import crontab

CELERY_IMPORTS = (
    'message.tasks',
    'event.tasks',
)

# celery
BROKER_URL = 'redis://localhost:6379/0'
CELERY_CACHE_BACKEND = 'redis://localhost:6379/1'
#CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

CELERYBEAT_SCHEDULE = {
    'every-minute': {
        'task': 'message.tasks.send_lost_messages_notification',
        'schedule': crontab(minute='*/1'),
        'args': (),
    },
}




WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
    }
}


SITE_URL = ''
LOGIN_URL = '/login/'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = SITE_URL + '/'


EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'atmyre@yandex.ru'
EMAIL_HOST_PASSWORD = os.environ['EMAIL_HOST_PASSWORD']