# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='text',
        ),
        migrations.AlterField(
            model_name='event',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='modification_date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation_date'),
        ),
    ]
