# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_membership_user_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='user_chat_id',
            field=models.IntegerField(),
        ),
    ]
